# Site settings
title: wecode.io blog
email: hello@wecode.io
description: > # this means to ignore newlines until "baseurl:"
  Where wecoders come to share our thoughts and experiences.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wecode.io" # the base hostname & protocol for your site
twitter_username: wecodeio
github_username:  wecodeio

# Build settings
markdown: kramdown

authors:
  delucas:
    name: Lucas Videla
    display_name: Lucas
    web: http://delucas.github.io
    twitter: luke_ar
    github: delucas